postgres:
	docker run --name bank-postgres -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=admin -d postgres

createdb:
	docker exec -it bank-postgres createdb --username=root --owner=root bank

dropdb:
	docker exec -it bank-postgres dropdb bank

migrateup:
	migrate -path db/migration -database "postgresql://root:admin@localhost:5432/bank?sslmode=disable" --verbose up

migratedown:
	migrate -path db/migration -database "postgresql://root:admin@localhost:5432/bank?sslmode=disable" --verbose down

sqlc:
	sqlc generate

test:
	go test -v -cover ./db/sqlc

server:
	go run ./main.go

mock:
	mockgen -package mockdb -destination store.go bank/db/sqlc Store
	mv ./store.go db/mock/store.go

.PHONY: postgres, createdb, dropdb, migrateup, migratedown, sqlc, server, mock